#ifndef CONSTANTS_H
#define CONSTANTS_H

#include<stdio.h>
#define SUCCESS 0
#define OK_SCANF 1
#define REALLOC_ERROR 2
#define MALLOC_ERROR 3
#define INPUT_ERROR 4
#define NOT_CORRECT_SIZE_OF_VAL 5
#define NOT_ENOUGH_ITEMS 6
#define NOT_CORRECT_POINTER 7
#define NOT_CORRECT_SIZE_FOR_MULTIPLY 8

#endif // CONSTANTS_H
